name: adv_flutter_ch2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: any
  blurrycontainer: any
  intl: any
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/chapter_logo.png"
  image_path_ios: "assets/chapter_logo.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/chapter_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/2.1/
    - assets/settings/
